export const screenLanguage = [
    {
        "id": "0",
        "lgn_code": "english",
        "know_about_medicinal_plant": "Medicinal Plants Directory",
        "know_your_nearest_utilities": "Know Your Nearest Utilities",
        "subsidy": 'Subsidy',
        "ask_an_expert": 'Post Your Query',
        "seed_indent": 'Seed Indent',
        "alerts": 'Alert',
        "notification": 'Notifications',
        "subsidy_update": 'Subsidy Update',
        "login_register": 'Login/Register',
        "logout": 'Logout',
        "welcome": 'Welcome!',
        "username": 'Username',
        "password": 'Password',
        "login": 'Login',
        "register": 'Register',
        "forgot_password": 'Forgot Password?',
        "please_enter_valid_username": 'Please enter valid Username',
        "please_enter_valid_password": 'Please enter valid Password',
        "geolocation": 'Nearest Utility',
        "govertment_of_telangana": 'Government Of Telangana',
        "tsmpb": 'TSMPB',
        "telangana_state_medicinal_plant_board": 'Telangana State Medicinal Plant Board',
        "department_Of_health": 'Department Of Health, Medical & Family welfare',
        "application_form_for_seeking": 'Application form for seeking financial assistance under National AYUSH Mission (NAM) on Medicinal Plants for cluster cultivation of medicinal crops',
        "terms_and_conditions": 'Terms & Conditions ',
        "cultivation_will_be_assisted": 'Cultivation will be assisted only in case of clusters. Each cultivation cluster will have minimum 2 hectare/ 5 acres of the land. Each cultivation cluster should be drawn from farmers having lands within a radius of not more than 15 km.',
        "farmers_of_cluster_group_should_mention": 'Farmers of cluster group should mention their community (SC/ST/BC/OC) is mandatory.',
        "the_complete_application_with_all_the_documents": 'The complete application with all the documents should be submitted in the online within the time period to avail the subsidy.',
        "check_list": 'Check List:',
        "aadhaar_card": 'Aadhaar card',
        "individual_bank_account": 'Individual bank account',
        "land_document": 'Land document (Eg. Land pass book, register document etc.)',
        "if_it_is_leased_land": 'If it is leased land, lease agreement along with pattadar pass book.',
        "note": 'Note :',
        "the_preference_for_release_of_subsidy": 'The preference for release of subsidy will be given on first-cum-first-serve basis.',
        "the_subsidy_will_be_given_only_to_the_crop": 'The subsidy will be given only to the crop available in the field during the field inspection.',
        "medicinal_plants_harvested_or_not_available": 'Medicinal plants harvested or not available on field during the field inspection are not eligible for subsidy.',
        "subsidy_will_be_released_as_per_the_National_Ayush_Mission": 'Subsidy will be released as per the National Ayush Mission (NAM) guideline and the unit cost per hectare specified by National Ayush Mission, Directorate, Ministry of Ayush, Government of India.',
        "applications_received_after_the_notified": 'Applications received after the notified date will not be accepted.',
        "agree_to_the_above_terms_and_conditions": 'I/We agree to the above terms and conditions.',
        "proceed_to_application": 'Proceed to Application',
        "cluster_resistration": 'Cluster Registration',
        "farmer_resistration": 'Farmer Registration',
        "apply_for_subsidy": 'Apply for Subsidy',
        "review_submit": 'Review & Submit',
        "name_of_the_cluster": 'Name of the Cluster',
        "state": 'State',
        "district": 'District',
        "mandal": 'Mandal',
        "tehsil": 'Tehsil',
        "village": 'Village',
        "pincode": 'Pin Code',
        "upload_declaration": 'Upload Declaration',
        "choose_file": 'Choose File',
        "please_provide_valid_name": 'Please Provide Valid Name',
        "please_provide_valid_pinCode": 'Please Provide Valid PinCode',
        "save_and_next": 'Save and Next',
        "personal_details": 'Personal Details',
        "select_your_role": 'Select Your Role',
        "leader": 'Leader',
        "member": 'Member',
        "cluster_name": "Cluster Name",
        "name_of_the_farmer": 'Name of the Farmer',
        "father_husband_name": 'Father/Husband Name',
        "gender": 'Gender',
        "male": 'Male',
        "female": 'Female',
        "category": 'Category',
        "aadhar_number": 'Aadhaar Number',
        "contact_details": 'Contact Details',
        "phone": 'Phone',
        "email": 'Email ID : (If Available)',
        "cultivation_land_details": 'Cultivation Land Details',
        "resister_farmer": 'Resister Farmer',
        "cluster": 'Cluster',
        "role": 'Role',
        "farmer_name": 'Farmer Name',
        "aadhar": 'Aadhaar',
        "fh_name": 'F/H Name',
        "edit": "Edit",
        "add_more_farmer": 'Add More Farmer',
        "delete_farmer": "Delete Farmer",
        "select_the_year": 'Select The Year',
        "farmer": 'Farmer',
        "crop_details": 'Crop Details',
        "crop_cultivated": 'Crop Cultivated',
        "no_of_acres": 'No. of Acres',
        "survey_no": 'Survey Number',
        "investment": "Investment/Acres",
        "upload_relavent_document": 'Upload Relavent Document',
        // "bank_details": 'Bank Details ',
        "account_number": 'Account Number',
        "name_of_the_bank": 'Name of The Bank',
        "name_of_the_branch": 'Name of The Branch',
        "ifsc_code": 'IFSC Code',
        "generate_pdf": 'Generate PDF',
        "locate_your_nearest_plants_centre": 'Locate Your Nearest Plants Centre',
        "nursery": 'Nursery',
        "storage_godown_and_drying_yards": 'Storage Godown and drying yards',
        "training_centre": 'Training Centre',
        "herbal_garden": 'Herbal Garden',
        "processing_unit_and_quality_esting_lab": "Processing Unit and Quality Testing lab",
        "submit": 'Submit',
        "around_you": 'Around You :',
        "medicinal_plants": 'Medicinal Plants',
        "scan": 'Scan',
        "home": 'Home',
        "plants_by_species": 'Plants By Species',
        "plants_by_families": 'Plants By Families',
        "view_all": 'View All',
        "search": 'Search',
        "select_state": 'Select State',
        "select_ownership": 'Select Ownership',
        "enter_name": 'Enter Name',
        "select_district": 'Select District',
        "enter_mandal": "Enter Mandal",
        "enter_tehsil": "Enter Tehsil",
        "enter_village": "Enter Village",
        "enter_pincode": "Enter Pin Code",
        "enter_farmer_name": 'Enter Farmer Name',
        "enter_father_husband_name": 'Enter Father/Husband name',
        "enter_aadhar_number": 'Enter Aadhaar no.',
        "enter_phone_number": 'Enter Phone no.',
        "enter_emailID": 'Enter EmailID',
        "select_farmer": 'Select Farmer',
        "select_crop": 'Select Crop :',
        "enter_number_of_acres": 'Enter no. of Acres',
        "enter_survey_number": 'Enter Survey no.',
        "enter_investment_acres": 'Enter Investment/Acres',
        "enter_account_number": 'Enter Account no.',
        "enter_name_of_the_bank": 'Enter name of the Bank',
        "enter_name_of_the_branch": 'Enter name of the Branch',
        "enter_ifsc_code": 'Enter IFSC Code',
        "Please_Provide_Valid_Number": 'Please Provide Valid Number',
        "Please_Provide_Valid_IFSC_Code": 'Please Provide Valid IFSC Code',
        "Please_Provide_Valid_Email_ID": "Please Provide Valid Email ID",
        "plants": 'Plants',
        "Market_info": 'Market Info',
        "delete": 'Delete',
        "wait": 'Wait',
        "plants_by_alphabet": 'Plants By Alphabet',

        "post_notification": 'Post Notification',
        "title": 'Title :',
        // "description": 'description',
        "title_must_be_less_than_characters": 'Title must be less than 100 characters',
        "description_should_be_less_than_characters": 'Description should be less than 15000 characters',
        "file_size_should_be_less_than_MB": 'File size should be less than 1 MB',
        "file": 'File',
        "please_login": 'Please Login',
        "alphabet": 'Alphabet',
        "filter": 'Filter',
        "local_name": 'Local Name',
        "scientific_name": 'Scientific Name',
        "botanical_description": 'Botanical Description',
        "habit": 'Habit',
        "leaf": 'Leaf',
        "inflorescence": 'Inflorescence',
        "select_plant": 'Select Plant',
        "search_by_common_name": 'Search By Common Name',
        "search_by_botanical_name": 'Search By Scientific Name',
        "search_by_parts_name": 'Search By Parts Name',
        "search_by_habit": 'Search By Habit',
        "search_by_medical_properties": 'Search By Medical Properties',
        "update_subsidy": 'UPDATE SUBSIDY',
        "caste": 'Caste :',
        "cultivation_address": 'Cultivation Address :',
        "mobile_num": 'Mobile Number :',
        "species": 'Species',
        "patta_passbook_survey_number": 'Patta Passbook Survey number :',
        "bank_details": 'Bank Details',
        "area_proposed": 'Area Proposed :',
        "actual_inspected_area": 'Actual Inspected Area',
        "gps_map": 'GPS Map',
        "sanctioned_subsidy_amount": 'Sanctioned Subsidy Amount',
        "remarks": 'Remarks',
        "verified": 'Verified :',
        "yes_no": 'YES/NO',
        "yes": 'YES',
        "no": 'NO',
        "type": 'Type...',

        "proceed": "PROCEED",
        "please_select_the_farmer": "Please select the Farmer",
        "mobile_number": "Mobile Number",
        "verified_all": "Verified All",
        "update_profile": "UPDATE PROFILE",
        "select_the_district": "Select the District",
        "select_the_mandal": "Select the Mandal",
        "select_the_cluster": "Select the Cluster",
        "select_the_farmer": "Select the Farmer",
        "echarak": "echarak",
        "locate_utilities": "Locate Utilities",
        "tsmpb_helpline": "TSMPB Helpline",
        "select": "Select",
        "not_selected": "Not Selected",
        "search_placeholder": "Search medicinal plants by their common or scientific name",
        "all": "ALL",
        "search_here": "Search here",
        "telangana": "Telangana",
        "andra_p": "Andhra Pradesh",
        "tamil_n": "Tamilnadu",
        "arunachal_p": "Arunachal Pradesh",
        "private": "Private",
        "government": "Goverment",
        "more_filters": "More Filters",
        "storage": "Storage",
        "warehouse": "Warehouse",
        "post": "Post",
        "harvest": "harvest",
        "centers": "Centers",
        "collection": "Collection",
        "ownership": "Ownership",
        "terms_and_conditions": "Terms and Conditions",
        "placeholder_name": "Enter the name",
        "placeholder_state": "Select the State",
        "placeholder_district": "Select the District",
        "placeholder_mandal": "Enter your mandal",
        "placeholder_tehsil": "Enter your tehsil",
        "placeholder_village": "Enter your village",
        "placeholder_pincode": "Enter the PinCode",
        "upload_declaration_text": "Upload Declaration on 10 Rs. Stamp paper",
        "placeholder_farmers_name": "Enter the Farmers's name",
        "placeholder_father_husband": "Enter Father/Husband's Name",
        // "category_oc":"OC",
        // "category_bc":"BC",
        // "category_sc":"SC",
        // "category_st":"ST",
        "upload_aadhaar": "Upload Aadhaar",
        "placeholder_doc_found_text": "No Document found",
        "residential_add": "Residential Address",
        "phone_number": "Phone Number",
        "locate_cultivation_land": "Location of Cultivation Land",
        "register_farmer": "Register Farmer",
        "family": "Family",
        "species_singular": "Species",
        "medicinal_plant_info": "Medicinal Plants Info",
        "receive_alerts": "Receive Alerts",
        "upload_farm_image": "Upload Farm Image",
        "placeholder_img_found_text": "No Image Found",
        "home_page":"Home Page",
        "show_all":"Show All",
        "botanical_name":"Botanical Name",
        "placeholder_homepage_search":"Search medicinal plants by their common or scientific name",
        "or":"(OR)",
        "title_plants_by_trade_name":"PLANTS BY TRADE NAME",
        "title_plants_by_botanical_name":"PLANTS BY BOTANICAL NAME",
        "title_plants_by_habit":"PLANTS BY HABIT",
        "title_plant_by_parts_name":"PLANTS BY PARTS NAME",
        "title_plants_by_medicinal_properties":"PLANTS BY MEDICINAL PROPERTIES",
        "title_all_plants_list":"ALL PLANTS LISTS",
        "title_all_species_list":"ALL SPECIES LISTS",
        "title_all_families_list":"ALL FAMILIES LISTS",
        "botanical_name":"Botanical Name :",
        "track_your_application":"Track Your Application",
        "update_inspection_report":"Update Inspection Report",
        "back":"Back",
        "application_id":"Application Id",
        "placeholder_enter_your_application_id":"Enter Your Application Id",
        "placeholder_enter_the_title_for_notification":"Enter the title for Notification",
        "summery":"Summery :",
        "placeholder_enter_the_summery_for_notification":"Enter the summery for Notification",
        "description":"Description :",
        "upload_image":"Upload Image :",
        "no_image_found":"No Image Found",
        "push_notification_form":"Push Notification Form",
        "show_notifications":"Show Notifications",
        "push_notifications":"Push Notifications",
        "update_inspected_report":"UPDATE INSPECTION REPORT",
        "return_to_subsidy_home":"Return to Subsidy Home",
        "back_to_home":"Back to Home",
        "view_inspection":"View Inspection",
        "pending_inspection":"Pending Inspection",
        "update_inspection":"Update Inspection",
        "upload_document":"Upload Document",
        "save":"Save",
        "next":"Next",
        "copy_of_the_farmers_bank_passbook":"Copy of the Farmer's Bank Passbook",
        "land_document_or_lease_document":"Land document (Eg. Land pass book, register document etc.) OR If it is leased land, lease agreement along with pattadar pass book.",
        "sort_by":"Sort By",
        "your_inspections":"Your Inspections",
        "district_name":"District Name",
        "view":"View",
        "update":"Update",
        "notification_type":"Notification Type :",
        "select_the_notification_type":"Select the Notification Type",
        "general_alerts":"General Alerts",
        "crop_advisories":"Crop Advisories",
        "training_info":"Training Info",
        "select_the_crop":"Select the Crop",
        "placeholder_search_for_clusters":"Search for Clusters",
        "market_info":"Market Information",
        "option_select_crop":"Select Crop",
        "family_singular":"Family",
        "placeholder_uploaded_sucessfully":"Uploaded Sucessfully",
        "add_more_subsidy":"Add More Subsidy",
        "delete_subsidy":"Delete Subsidy",
        "plant_details":"Plant Details",
        "chemical_constituents":"Chemical Constituents",
        "flowering":"Flowering",
        "fruiting":"Fruiting",
        "growing_details":"Growing Details",
        "medicinal_uses":"Medicinal Uses",
        "parts_used":"Parts Used",
        "select_storage_location_type":"Select Storage Location Type",
        "select_state_and_ownership":"Select State & Ownership",
        "storage_godown":"Storage Godown",
        "drying_yards":"& Drying Yards",
        "processing_unit":"Processing Unit",
        "quality_testing":"& Quality Testing",
        "lab":"Lab",
        "alert_please_select_proper_filter":"Please select proper filter",
        "alert_no_clusters_found_for_selected_filters":"No clusters found for selected filters",
        "alert_input_fields_cannot_be_blank":"Input fields cannot be blank!",
        "alert_subsidy_details_added":"Subsidy Details Added",
        "alert_land_document_uploaded_successfully":"Land Document Uploaded Successfully!",
        "alert_bank_document_uploaded_successfully":"Bank Document Uploaded Successfully!",
        "alert_no_data_left_for_adding":"no data left for adding",
        "alert_farmer_details_added":"Farmer Details Added",
        "alert_file_uploaded_successfully":"File Uploaded Successfully!",
        "alert_inspection_report_updated":"Inspection Report Updated",
        "alert_no_farmers_for_that_particular_cluster":"No Farmers for that particular cluster",
        "alert_inspection_has_been_done":"Inspection has been done",
        "alert_title_can_not_be_empty":"Title can not be empty",
        "alert_summery_can_not_be_empty":"Summery can not be empty",
        "alert_please_select_notification_type":"Please Select Notification Type",
        "alert_please_select_crop":"Please select crop",
        "alert_notification_posted":"Notification Posted",
        "alert_no_pending_famers":"No pending Famers",
        "applied":"Applied",
        "inspected":"Inspected",
        "released":"Released",



        

    },
    {
        "id": "1",
        "lgn_code": "telugu",
        "know_about_medicinal_plant": "ఔషధ మొక్కల గురించి తెలుసుకోండి",
        "know_your_nearest_utilities": "మీ సమీప యుటిలిటీలను తెలుసుకోండి",
        "subsidy": 'సబ్సిడీ',
        "ask_an_expert": 'నిపుణుడిని సంప్రదించండి',
        "seed_indent": 'విత్తనం ఇండెంట్',
        "alerts": 'అప్రమత్తం',
        "notification": 'నోటిఫికేషన్',
        "subsidy_update": 'సబ్సిడీ నవీకరణ',
        "login_register": 'లాగ్అవుట్/నమోదు',
        "logout": 'లాగ్అవుట్',
        "geolocation": 'సమీప యుటిలిటీ',
        "govertment_of_telangana": 'తెలంగాణ ప్రభుత్వం',
        "tsmpb": 'టిఎస్ఎంపిబి',
        "welcome": 'స్వాగతం!',
        "username": 'వినియోగదారు పేరు',
        "password": 'పాస్వర్డ్',
        "login": 'లాగ్ ఇన్ ',
        "register": 'నమోదు',
        "forgot_password": 'పాస్వర్డ్ మర్చిపోయాను',
        "please_enter_valid_username": 'దయచేసి చెల్లుబాటు అయ్యే వినియోగదారు పేరును నమోదు చేయండి',
        "please_enter_valid_password": 'దయచేసి చెల్లుబాటు అయ్యే పాస్‌వర్డ్‌ను నమోదు చేయండి',
        "telangana_state_medicinal_plant_board": 'తెలంగాణ రాష్ట్ర ఔషధ మొక్కల బోర్డు',
        "department_Of_health": 'ఆరోగ్య, వైద్య & కుటుంబ సంక్షేమ శాఖ',
        "application_form_for_seeking": 'ఔషధ పంటల సమూహ సాగు కోసం ఔషధ మొక్కలపై జాతీయ ఆయుష్ మిషన్ (నామ్) కింద ఆర్థిక సహాయం కోసం దరఖాస్తు ఫారమ్',
        "terms_and_conditions": 'నిబంధనలు మరియు షరతులు ',
        "cultivation_will_be_assisted": 'క్లస్టర్ల విషయంలో మాత్రమే సాగుకు సహాయం అందించబడుతుంది. ప్రతి సాగు క్లస్టర్‌లో కనీసం 2 హెక్టార్లు/ 5 ఎకరాల భూమి ఉంటుంది. ప్రతి సాగు క్లస్టర్‌ను 15 కి.మీ కంటే ఎక్కువ పరిధిలో భూములు ఉన్న రైతుల నుంచి తీసుకోవాలి.',
        "farmers_of_cluster_group_should_mention": 'క్లస్టర్ గ్రూపులోని రైతులు తమ సంఘం (SC/ST/BC/OC) తప్పనిసరి అని పేర్కొనాలి.',
        "the_complete_application_with_all_the_documents": 'సబ్సిడీని పొందేందుకు అన్ని పత్రాలతో కూడిన పూర్తి దరఖాస్తును గడువులోపు ఆన్‌లైన్‌లో సమర్పించాలి',
        "check_list": 'తనిఖీ జాబితా:',
        "aadhaar_card": 'ఆధార్ కార్డు',
        "individual_bank_account": 'వ్యక్తిగత బ్యాంకు ఖాతా',
        "land_document": 'భూమి పత్రం (ఉదా. భూమి పాస్ పుస్తకం, రిజిస్టర్ డాక్యుమెంట్ మొదలైనవి)',
        "if_it_is_leased_land": 'కౌలు భూమి అయితే పట్టాదార్ పాస్ పుస్తకంతో పాటు లీజు అగ్రిమెంట్.',
        "note": 'గమనిక :',
        "the_preference_for_release_of_subsidy": 'సబ్సిడీ విడుదలకు ప్రాధాన్యత ఫస్ట్-కమ్-ఫస్ట్-సర్వ్ ప్రాతిపదికన ఇవ్వబడుతుంది.',
        "the_subsidy_will_be_given_only_to_the_crop": 'క్షేత్ర పరిశీలనలో పొలంలో లభించే పంటకు మాత్రమే సబ్సిడీ ఇస్తారు.',
        "medicinal_plants_harvested_or_not_available": 'క్షేత్ర పరిశీలన సమయంలో పండించిన లేదా పొలంలో అందుబాటులో లేని ఔషధ మొక్కలు సబ్సిడీకి అర్హులు కాదు.',
        "subsidy_will_be_released_as_per_the_National_Ayush_Mission": 'జాతీయ ఆయుష్ మిషన్ (NAM) మార్గదర్శకం మరియు జాతీయంగా పేర్కొన్న హెక్టారుకు యూనిట్ ధర ప్రకారం సబ్సిడీ విడుదల చేయబడుతుంది ఆయుష్ మిషన్, డైరెక్టరేట్, ఆయుష్ మంత్రిత్వ శాఖ, భారత ప్రభుత్వం.',
        "applications_received_after_the_notified": 'దరఖాస్తు తేదీ ముగిసిన తర్వాత వచ్చిన దరఖాస్తులు అంగీకరించబడవు.',
        "agree_to_the_above_terms_and_conditions": 'నేను/మేము పైనున్నా  నిబంధనలు మరియు షరతులను అంగీకరిస్తున్నాము.',
        "proceed_to_application": 'దరఖాస్తును కొనసాగండి',
        "cluster_resistration": 'క్లస్టర్ నమోదు',
        "farmer_resistration": 'రైతు నమోదు',
        "apply_for_subsidy": 'సబ్సిడీ కి దరఖాస్తు చేసుకోండి',
        "review_submit": 'సమీక్షించండి & సమర్పించండి',
        "name_Of_the_cluster": 'క్లస్టర్ పేరు',
        "state": 'రాష్ట్రం',
        "district": 'జిల్లా',
        "mandal": 'మండలం',
        "tehsil": 'తహసీల్',
        "village": 'గ్రామం',
        "pincode": 'పిన్ కోడ్',
        "upload_declaration": 'వాంగ్మూలం అప్లోడ్ చెయ్యండి',
        "choose_file": 'ఫైల్‌ని ఎంచుకోండి',
        "please_provide_valid_name": 'దయచేసి చెల్లుబాటు అయ్యే పేరును అందించండి',
        "please_provide_valid_pinCode": 'దయచేసి చెల్లుబాటు అయ్యే పిన్‌కోడ్‌ని అందించండి',
        "save_and_next": 'సేవ్ మరియు తదుపరి',
        "personal_details": 'వ్యక్తిగత సమాచారం',
        "select_your_role": 'మీ పాత్రను ఎంచుకోండి',
        "leader": 'నాయకుడు',
        "member": 'సభ్యుడు',
        "cluster_name": "క్లస్టర్ పేరు",
        "name_of_the_farmer": 'రైతు పేరు',
        "father_husband_name": 'తండ్రి/భర్త పేరు',
        "gender": 'లింగం',
        "male": 'పురుషుడు',
        "female": 'స్త్రీ',
        "category": 'వర్గం',
        "aadhar_number": 'ఆధార్ సంఖ్య',
        "contact_details": 'సంప్రదింపు వివరాలు',
        "phone": 'ఫోన్',
        "email": 'ఇమెయిల్ ID : (అందుబాటులో ఉంటే)',
        "cultivation_land_details": 'సాగు భూమి వివరాలు',
        "resister_farmer": 'రైతును నమోదు చేయండి',
        "cluster": 'క్లస్టర్',
        "role": 'పాత్ర',
        "farmer_name": 'రైతు పేరు',
        "aadhar": 'ఆధార్',
        "fh_name": 'F/H పేరు',
        "edit": "సవరించు",
        "add_more_farmer": 'మరి కొందరి రైతులను జోడించండి',
        "delete_farmer": "రైతును తొలగించండి",
        "select_the_year": 'సంవత్సరాన్ని ఎంచుకోండి',
        "farmer": 'రైతు',
        "crop_details": 'పంట వివరాలు',
        "crop_cultivated": 'పంట సాగు చేశారు',
        "no_of_acres": 'ఎకరాల సంఖ్య',
        "survey_no": 'సర్వే సంఖ్య',
        "investment": "పెట్టుబడి/ఎకరాలు",
        "upload_relavent_document": 'సంబంధిత పత్రాన్ని అప్‌లోడ్ చేయండి',
        "account_number": 'ఖాతా సంఖ్య',
        "name_of_the_bank": 'బ్యాంక్ పేరు',
        "name_of_the_branch": 'శాఖ పేరు',
        "ifsc_code": 'IFSC కోడ్',
        "generate_pdf": 'PDFని రూపొందించండి',
        "locate_your_nearest_plants_centre": 'మీ సమీప మొక్కల కేంద్రాన్ని గుర్తించండి',
        "nursery": 'నర్సరీ',
        "storage_godown_and_drying_yards": 'నిల్వ గోడౌన్ మరియు డ్రైయింగ్ యార్డులు',
        "training_centre": 'శిక్షణ కేంద్రం',
        "herbal_garden": 'మూలికా తోట',
        "processing_unit_and_quality_esting_lab": "ప్రాసెసింగ్ యూనిట్ మరియు నాణ్యత పరీక్ష ల్యాబ్",
        "submit": 'సమర్పించండి',
        "around_you": 'మీ చుట్టూ :',
        "medicinal_plants": 'ఔషధ మొక్కలు',
        "scan": 'స్కాన్',
        "home": 'హోమ్',
        "plants_by_species": 'జాతుల వారీగా మొక్కలు',
        "plants_by_families": 'కుటుంబాల వారీగా మొక్కలు',
        "view_all": 'అన్నీ చూడండి',
        "search": 'వెతకండి',
        "select_state": 'రాష్ట్రాన్ని ఎంచుకోండి',
        "select_ownership": 'యాజమాన్యాన్ని ఎంచుకోండి',
        "enter_name": 'పేరు నమోదు చేయండి',
        "select_district": 'జిల్లాను ఎంచుకోండి',
        "enter_mandal": "మండలం  నమోదు చేయండి",
        "enter_tehsil": "తహసీల్ని నమోదు చెయ్యండి  ",
        "enter_village": "గ్రామం నమోదు చెయ్యండి  ",
        "enter_pincode": "పిన్‌కోడ్‌ని నమోదు చేయండి",
        "enter_farmer_name": 'రైతు పేరు నమోదు చేయండి',
        "enter_father_husband_name": 'తండ్రి/భర్త పేరు నమోదు చేయండి',
        "enter_aadhar_number": 'ఆధార్ నంబర్‌ని నమోదు చేయండి',
        "enter_phone_number": 'ఫోన్ నంబర్‌ని నమోదు చేయండి',
        "enter_emailID": 'ఇమెయిల్ ఐడిని నమోదు చేయండి',
        "select_farmer": 'రైతును ఎంచుకోండి',
        "select_crop": 'పంటను ఎంచుకోండి :',
        "enter_number_of_acres": 'ఎకరాల సంఖ్యను నమోదు చేయండి',
        "enter_survey_number": 'సర్వే నంబర్‌ను నమోదు చేయండి',
        "enter_investment_acres": 'పెట్టుబడి/ఎకరాలను నమోదు చేయండి',
        "enter_account_number": 'ఖాతా సంఖ్యను నమోదు చేయండి',
        "enter_name_of_the_bank": 'బ్యాంకు పేరును నమోదు చేయండి',
        "enter_name_of_the_branch": 'శాఖ పేరు నమోదు చేయండి',
        "enter_ifsc_code": 'ifsc కోడ్‌ని నమోదు చేయండి',
        "Please_Provide_Valid_Number": 'దయచేసి చెల్లుబాటు అయ్యే నంబర్‌ను అందించండి',
        "Please_Provide_Valid_IFSC_Code": 'దయచేసి చెల్లుబాటు అయ్యే IFSC కోడ్‌ను అందించండి',
        "Please_Provide_Valid_Email_ID": "దయచేసి చెల్లుబాటు అయ్యే ఇమెయిల్ IDని అందించండి",
        "plants": 'మొక్కలు',
        "Market_info": 'మార్కెట్ సమాచారం',
        "delete": 'తొలగించు',
        "wait": 'వేచి ఉండండి',
        "plants_by_alphabet": 'వర్ణమాల ద్వారా మొక్కలు',
        "please_select_the_farmer": "దయచేసి రైతును ఎంచుకోండి",
        "mobile_number": "మొబైల్ నంబర్",
        "actual_inspection_area": "వాస్తవ తనిఖీ ప్రాంతం",
        "verified_all": "అన్నీ ధృవీకరించబడ్డాయి",
        "update_profile": "ప్రొఫైల్ అప్‌డేట్ చేయండి",
        "select_the_district": "జిల్లాను ఎంచుకోండి",
        "select_the_mandal": "మండలిని ఎంచుకోండి",
        "select_the_cluster": "క్లస్టర్‌ని ఎంచుకోండి",
        "select_the_farmer": "రైతును ఎంచుకోండి",
        "echarak": "ఈచరక్",
        "locate_utilities": "యుటిలిటీలను గుర్తించండి",
        "tsmpb_helpline": "TSMPB హెల్ప్‌లైన్",
        "select": "ఎంచుకోండి",
        "not_selected": "ఎంపిక చేయబడలేదు",
        "all": "అన్ని",
        "search_here": "ఇక్కడ వెతకండి",
        "telangana": "తెలంగాణ",
        "andra_p": "ఆంధ్రప్రదేశ్",
        "tamil_n": "తమిళనాడు",
        "arunachal_p": "అరుణాచల్ ప్రదేశ్",
        "private": "ప్రైవేట్",
        "government": "ప్రభుత్వం",
        "more_filters": "మరిన్ని ఫిల్టర్‌లు",
        "storage": "నిల్వ",
        "warehouse": "గిడ్డంగి",
        "post": "పోస్ట్ చేయండి",
        "harvest": "పంట",
        "centers": "కేంద్రాలు",
        "collection": "సేకరణలు",
        "ownership": "యాజమాన్యం",
        "terms_and_conditions": "నిబంధనలు మరియు షరతులు",
        "placeholder_name": "పేరును నమోదు చేయండి",
        "placeholder_state": "రాష్ట్రాన్ని ఎంచుకోండి",
        "placeholder_mandal": "మీ మండలాన్ని నమోదు చేయండి",
        "placeholder_district": "జిల్లాను ఎంచుకోండి",
        "placeholder_tehsil": "మీ తహసీల్‌ని నమోదు చేయండి",
        "placeholder_village": "మీ గ్రామంలో ప్రవేశించండి",
        "placeholder_pincode": "పిన్‌కోడ్‌ని నమోదు చేయండి",
        "upload_declaration_text": "10 రూపై డిక్లరేషన్‌ను అప్‌లోడ్ చేయండి. స్టాంప్ పేపర్",
        "cluster_registration": 'క్లస్టర్ రెసిస్ట్రేషన్',
        "placeholder_farmers_name": "రైతుల పేరు నమోదు చేయండి",
        "placeholder_father_husband": "తండ్రి/భర్త పేరు నమోదు చేయండి",
        "upload_aadhaar": "ఆధార్‌ను అప్‌లోడ్ చేయండి",
        "placeholder_doc_found_text": "పత్రం ఏదీ కనుగొనబడలేదు",
        "residential_add": "నివాస చిరునామా",
        "phone_number": "ఫోను నంబరు",
        "locate_cultivation_land": "సాగు భూమి యొక్క స్థానం",
        "register_farmer": "రైతును నమోదు చేయండి",
        "medicinal_plant_info": "ఔషధ మొక్కల సమాచారం",
        "receive_alerts": "హెచ్చరికలను స్వీకరించండి",
        "upload_farm_image": "వ్యవసాయ చిత్రాన్ని అప్‌లోడ్ చేయండి",
        "placeholder_img_found_text": "చిత్రం ఏదీ కనుగొనబడలేదు",
        "home_page":"హోమ్ పేజీ",
        "show_all":"అన్నీ చూపండి",
        "botanical_name":"బొటానికల్ పేరు",
        "placeholder_homepage_search":"ఔషధ మొక్కలను వాటి సాధారణ లేదా శాస్త్రీయ నామంతో శోధించండి",
        "or":"(లేదా)",
        "title_plants_by_trade_name":"వాణిజ్య పేరు ద్వారా మొక్కలు",
        "title_plants_by_botanical_name":"బొటానికల్ పేరు ద్వారా మొక్కలు",
        "title_plants_by_habit":"అలవాటు ద్వారా మొక్కలు",
        "title_plant_by_parts_name":"పార్ట్‌ల పేరుతో మొక్కలు",
        "title_plants_by_medicinal_properties":"ఔషధ గుణాల ద్వారా మొక్కలు",
        "title_all_plants_list":"అన్ని మొక్కల జాబితాలు",
        "title_all_species_list":"అన్ని జాతుల జాబితాలు",
        "title_all_families_list":"అన్ని కుటుంబాల జాబితాలు",
        "botanical_name":"బొటానికల్ పేరు :",
        "track_your_application":"మీ అప్లికేషన్‌ను ట్రాక్ చేయండి",
        "update_inspection_report":"తనిఖీ నివేదికను నవీకరించండి",
        "back":"వెనుకకు",
        "application_id":"అప్లికేషన్ Id",
        "placeholder_enter_your_application_id":"మీ అప్లికేషన్ ఐడిని నమోదు చేయండి",
        "title":"శీర్షిక :",
        "placeholder_enter_the_title_for_notification":"నోటిఫికేషన్ కోసం శీర్షికను నమోదు చేయండి",
        "summery":"వేసవి :",
        "placeholder_enter_the_summery_for_notification":"నోటిఫికేషన్ కోసం సమ్మరీని నమోదు చేయండి",
        "description":"వివరణ :",
        "upload_image":"చిత్రాన్ని అప్‌లోడ్ చేయండి :",
        "no_image_found":"చిత్రం ఏదీ కనుగొనబడలేదు",
        "post_notification":'పోస్ట్ నోటిఫికేషన్',
        "push_notification_form":"పుష్ నోటిఫికేషన్ ఫారమ్",
        "show_notifications":"నోటిఫికేషన్‌లను చూపించు",
        "push_notifications":"పుష్ నోటిఫికేషన్లు",
        "update_inspected_report":"తనిఖీ నివేదికను నవీకరించండి",
        "return_to_subsidy_home":"సబ్సిడీ హోమ్‌కి తిరిగి వెళ్ళు",
        "back_to_home":"తిరిగి ఇంటికి",
        "view_inspection":"తనిఖీని వీక్షించండి",
        "pending_inspection":"పెండింగ్‌లో ఉన్న తనిఖీ",
        "update_inspection":"తనిఖీని నవీకరించండి",
        "name_of_the_cluster": 'క్లస్టర్ పేరు',
        "upload_document":"పత్రాన్ని అప్‌లోడ్ చేయండి",
        "save":"సేవ్ చేయండి",
        "next":"తరువాత",
        "copy_of_the_farmers_bank_passbook":"రైతు బ్యాంకు పాస్‌బుక్ కాపీ",
        "land_document_or_lease_document":"భూమి పత్రం (ఉదా. భూమి పాస్ పుస్తకం, రిజిస్టర్ డాక్యుమెంట్ మొదలైనవి) లేదా అది లీజుకు తీసుకున్న భూమి అయితే, పట్టాదార్ పాస్ పుస్తకంతో పాటు లీజు ఒప్పందం.",
        "sort_by":"ఆమరిక",
        "your_inspections":"మీ తనిఖీలు",
        "district_name":"జిల్లా పేరు",
        "view":"చూడండి",
        "update":"నవీకరించు",
        "notification_type":"నోటిఫికేషన్ రకం :",
        "select_the_notification_type":"నోటిఫికేషన్ రకాన్ని ఎంచుకోండి",
        "general_alerts":"సాధారణ హెచ్చరికలు",
        "crop_advisories":"పంట సలహాలు",
        "training_info":"శిక్షణ సమాచారం",
        "select_the_crop":"పంటను ఎంచుకోండి",
        "placeholder_search_for_clusters":"క్లస్టర్‌ల కోసం శోధించండి",
        "market_info":"మార్కెట్ సమాచారం",
        "option_select_crop":"కత్తిరించు ఎంచుకోండి",
        "family_singular":"కుటుంబం",
        "placeholder_uploaded_sucessfully":"విజయవంతంగా అప్‌లోడ్ చేయబడింది",
        "add_more_subsidy":"మరింత సబ్సిడీని జోడించండి",
        "delete_subsidy":"సబ్సిడీని తొలగించండి",
        "plant_details":"మొక్కల వివరాలు",
        "chemical_constituents":"రసాయన భాగాలు",
        "flowering":"పుష్పించే",
        "fruiting":"ఫలాలు కాస్తాయి",
        "growing_details":"పెరుగుతున్న వివరాలు",
        "medicinal_uses":"ఔషధ ఉపయోగాలు",
        "parts_used":"వాడిన భాగాలు",
        "select_state_and_ownership":"రాష్ట్రం & యాజమాన్యాన్ని ఎంచుకోండి",
        "select_storage_location_type":"నిల్వ స్థాన రకాన్ని ఎంచుకోండి",
        "storage_godown":"నిల్వ గోడౌన్",
        "drying_yards":"& డ్రైయింగ్ యార్డ్స్",
        "processing_unit":"ప్రాసెసింగ్ యూనిట్",
        "quality_testing":"& నాణ్యత పరీక్ష",
        "lab":"ప్రయోగశాల",
        "alert_please_select_proper_filter":"దయచేసి సరైన ఫిల్టర్‌ని ఎంచుకోండి",
        "alert_no_clusters_found_for_selected_filters":"ఎంచుకున్న ఫిల్టర్‌ల కోసం క్లస్టర్‌లు ఏవీ కనుగొనబడలేదు",
        "alert_input_fields_cannot_be_blank":"ఇన్‌పుట్ ఫీల్డ్‌లు ఖాళీగా ఉండకూడదు!",
        "alert_subsidy_details_added":"సబ్సిడీ వివరాలు జోడించబడ్డాయి",
        "alert_land_document_uploaded_successfully":"భూమి పత్రం విజయవంతంగా అప్‌లోడ్ చేయబడింది!",
        "alert_bank_document_uploaded_successfully":"బ్యాంక్ పత్రం విజయవంతంగా అప్‌లోడ్ చేయబడింది!",
        "alert_no_data_left_for_adding":"జోడించడానికి డేటా లేదు",
        "alert_farmer_details_added":"రైతు వివరాలు జోడించబడ్డాయి",
        "alert_file_uploaded_successfully":"ఫైల్ విజయవంతంగా అప్‌లోడ్ చేయబడింది!",
        "alert_inspection_report_updated":"తనిఖీ నివేదిక నవీకరించబడింది",
        "alert_no_farmers_for_that_particular_cluster":"నిర్దిష్ట క్లస్టర్‌కు రైతులు లేరు",
        "alert_inspection_has_been_done":"తనిఖీ జరిగింది",
        "alert_title_can_not_be_empty":"శీర్షిక ఖాళీగా ఉండకూడదు",
        "alert_summery_can_not_be_empty":"వేసవి ఖాళీగా ఉండకూడదు",
        "alert_please_select_notification_type":"దయచేసి నోటిఫికేషన్ రకాన్ని ఎంచుకోండి",
        "alert_please_select_crop":"దయచేసి కత్తిరించు ఎంచుకోండి",
        "alert_notification_posted":"నోటిఫికేషన్ పోస్ట్ చేయబడింది",
        "alert_no_pending_famers":"పెండింగ్‌లో ఉన్న ఫామర్‌లు లేవు",
        "applied":"దరఖాస్తు చేసుకున్నారు",
        "inspected":"తనిఖీ చేశారు",
        "released":"విడుదలైంది",






        "title_must_be_less_than_characters": 'శీర్షిక తప్పనిసరిగా 100 అక్షరాల కంటే తక్కువ ఉండాలి',
        "description_should_be_less_than_characters": 'వివరణ 15000 అక్షరాల కంటే తక్కువ ఉండాలి',
        "file_size_should_be_less_than_MB": 'ఫైల్ పరిమాణం 1 MB కంటే తక్కువగా ఉండాలి',
        "file": 'ఫైల్',
        "please_login": 'దయచేసి లాగిన్ చేయండి',
        "alphabet": 'వర్ణమాల',
        "filter": 'ఫిల్టర్ చేయండి',
        "local_name": 'స్థానిక పేరు',
        "scientific_name": 'శాస్త్రీయ నామం',
        "botanical_description": 'బొటానికల్ వివరణ',
        "habit": 'అలవాటు',
        "leaf": 'ఆకు',
        "inflorescence": 'పుష్పగుచ్ఛము',
        "select_plant": 'మొక్కను ఎంచుకోండి',
        "search_by_common_name": 'సాధారణ పేరు ద్వారా శోధించండి',
        "search_by_botanical_name": 'శాస్త్రీయ పేరు ద్వారా శోధించండి',
        "search_by_parts_name": 'భాగాల పేరు ద్వారా శోధించండి',
        "search_by_habit": 'అలవాటు ద్వారా శోధించండి',
        "search_by_medical_properties": 'వైద్య లక్షణాల ద్వారా శోధించండి',
        "update_subsidy": 'సబ్సిడీని నవీకరించండి',
        "caste": 'కులం',
        "proceed": 'కొనసాగండి',
        "cultivation_address": 'సాగు చిరునామా',
        "mobile_num": 'మొబైల్ నంబర్',
        "species": 'జాతులు',
        "species_singular": "జాతి",
        "patta_passbook_survey_number": 'పట్టా పాస్‌బుక్ సర్వే నంబర్',
        "bank_details": 'బ్యాంక్ వివరములు',
        "area_proposed": 'ప్రతిపాదిత ప్రాంతం',
        "actual_inspected_area": 'వాస్తవ తనిఖీ ప్రాంతం',
        "gps_map": 'GPS మ్యాప్',
        "sanctioned_subsidy_amount": 'మంజూరు చేయబడిన సబ్సిడీ మొత్తం',
        "remarks": 'వ్యాఖ్యలు',
        "verified": 'ధృవీకరించబడింది',
        "yes_no": 'అవును కాదు',
        "yes": 'అవును',
        "no": 'నం',
        "type": 'టైప్ చేయండి',
        "search_placeholder": "ఔషధ మొక్కలను వాటి సాధారణ లేదా బొటానికల్ పేరుతో శోధించండి",
        "family": "కుటుంబం",
        "general_alerts" :"సమాచారం",
        "crop_advisories":"పంట సలహాలు",
        "training_info":"శిక్షణ సమాచారం",


    }
]
